# check

["beeai-web:check"]
depends = ["beeai-web:check:*"]

["beeai-web:check:next"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm next lint"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:check:prettier"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm prettier --log-level silent --check src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

["beeai-web:check:eslint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm eslint src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:check:tsc"]
depends = ["common:setup:pnpm", "beeai-web:check:next"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm tsc --noEmit -p tsconfig.json"
sources = ["src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:check:stylelint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm stylelint src/**/*.css src/**/*.scss"
sources = ["src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

# fix

["beeai-web:fix"]
depends = ["beeai-web:fix:*"]

["beeai-web:fix:prettier"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm prettier --log-level silent --write src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx", "src/**/*.html", "src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

["beeai-web:fix:eslint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm eslint --fix src"
sources = ["src/**/*.js", "src/**/*.jsx", "src/**/*.ts", "src/**/*.tsx"]
outputs = { auto = true }

["beeai-web:fix:stylelint"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm stylelint --fix=lax src/**/*.css src/**/*.scss"
sources = ["src/**/*.css", "src/**/*.scss"]
outputs = { auto = true }

# run

["beeai-web:run"]
description = "NOTE: You also need to have `beeai-server` running for the backend"
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm dev"

# build

["beeai-web:build"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm build"
sources = ["*.json", "*.js", "index.html", "src/**/*.tsx", "src/**/*.ts"]
outputs = { auto = true }

# preview

["beeai-web:preview"]
depends = ["common:setup:pnpm"]
dir = "{{config_root}}/apps/beeai-web"
run = "pnpm preview"

# clean

["beeai-web:clean"]
dir = "{{config_root}}/apps/beeai-web"
run = "rm -rf ./.next"
