# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""switch to a2a protocol

Revision ID: 644ccacc48f3
Revises: 975813acde2a
Create Date: 2025-07-14 16:42:07.098361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "644ccacc48f3"
down_revision: str | None = "975813acde2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE agents CASCADE")
    op.execute("DROP TABLE agent_requests CASCADE")

    # BREAKING CHANGE - switch to A2A - delete all providers
    op.execute("TRUNCATE TABLE providers CASCADE")

    op.drop_column("providers", "env")
    op.add_column("providers", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("providers", sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("providers", sa.Column("agent_card", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise NotImplementedError("Cannot downgrade to pre-a2a version")
