# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add text_extractions table and file type enums

Revision ID: 8b2065340855
Revises: 246e011dd64e
Create Date: 2025-06-27 14:14:36.567663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b2065340855"
down_revision: str | None = "246e011dd64e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


extraction_status_enum = sa.Enum("pending", "in_progress", "completed", "failed", "cancelled", name="extraction_status")
file_type_enum = sa.Enum("user_upload", "extracted_text", name="file_type")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_extractions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("extracted_file_id", sa.UUID(), nullable=True),
        sa.Column("status", extraction_status_enum, nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("extraction_metadata", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["extracted_file_id"], ["files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    file_type_enum.create(op.get_bind())
    op.add_column("files", sa.Column("file_type", file_type_enum, nullable=False))
    op.add_column("files", sa.Column("parent_file_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "files", "files", ["parent_file_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "files", type_="foreignkey")
    op.drop_column("files", "parent_file_id")
    op.drop_column("files", "file_type")
    op.drop_table("text_extractions")
    extraction_status_enum.drop(op.get_bind())
    file_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
