# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""empty message

Revision ID: 975813acde2a
Revises: 327991a3c7a7
Create Date: 2025-07-17 15:39:56.507771

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "975813acde2a"
down_revision: str | None = "327991a3c7a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("input_content_types", sa.JSON(), nullable=True))
    op.add_column("agents", sa.Column("output_content_types", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "output_content_types")
    op.drop_column("agents", "input_content_types")
    # ### end Alembic commands ###
