# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add acp_session_id to agent_requests

Revision ID: b8f8a7190ab9
Revises: 638be28ea3f9
Create Date: 2025-06-25 13:06:49.379517

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8f8a7190ab9"
down_revision: str | None = "638be28ea3f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_requests", sa.Column("acp_session_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_requests", "acp_session_id")
    # ### end Alembic commands ###
