# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""empty message

Revision ID: f5d08cbe4ef8
Revises: cb9dc6ddcd3c
Create Date: 2025-05-19 14:26:20.564132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5d08cbe4ef8"
down_revision: Union[str, None] = "cb9dc6ddcd3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("providers", sa.Column("auto_remove", sa.Boolean(), nullable=True))
    op.execute("UPDATE providers SET auto_remove = false")
    op.alter_column("providers", "auto_remove", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("providers", "auto_remove")
    # ### end Alembic commands ###
