# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

"""add auto_remove column to providers

Revision ID: f5d08cbe4ef8
Revises: cb9dc6ddcd3c
Create Date: 2025-05-19 14:26:20.564132

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5d08cbe4ef8"
down_revision: str | None = "cb9dc6ddcd3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("providers", sa.Column("auto_remove", sa.Boolean(), nullable=True))
    op.execute("UPDATE providers SET auto_remove = false")
    op.alter_column("providers", "auto_remove", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("providers", "auto_remove")
    # ### end Alembic commands ###
