# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

from typing import runtime_checkable, Protocol, AsyncContextManager, AsyncIterator
from uuid import UUID

from beeai_server.domain.models.file import File, AsyncFile


class IFileRepository(Protocol):
    async def list(self, user_id: UUID | None = None) -> AsyncIterator[File]: ...
    async def create(self, *, file: File) -> None: ...
    async def total_usage(self, *, user_id: UUID | None = None) -> int: ...
    async def get(self, *, file_id: UUID, user_id: UUID) -> File: ...
    async def delete(self, *, file_id: UUID, user_id: UUID) -> None: ...


@runtime_checkable
class IObjectStorageRepository(Protocol):
    async def upload_file(self, *, file_id: UUID, file: AsyncFile) -> int: ...
    async def get_file(self, *, file_id: UUID) -> AsyncContextManager[AsyncFile]: ...
    async def delete_file(self, *, file_id: UUID) -> None: ...
    async def get_file_url(self, *, file_id: UUID) -> str: ...
