name: ACP Typescript SDK

on:
  push:
    tags:
      - "acp-v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise acp-typescript-sdk:build
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          pnpm publish --access public --no-git-checks
        working-directory: packages/acp-typescript-sdk
        env:
          NPM_CONFIG_PROVENANCE: true # https://github.com/pnpm/pnpm/issues/6435#issuecomment-1518397267
